---
- name: create directory
  file:
    path: "~/dane"
    state: directory
    mode: "0700"

- name: creating files
  file:
    path: "~/dane/{{ item }}"
    state: touch
  with_items:
    - tajne
    - poufne
    - publiczne

- name: run ls
  shell: ls -l
  args:
    chdir: "~/dane"
  register: result

- debug:
    var: result
  #with items: result.stdout_lines