Vagrant.configure("2") do |config|
    config.vm.box_check_update = false
    config.vagrant.plugins = "vagrant-share"
  
    config.vm.define "node" do |node|
      node.vm.hostname = "node"
      node.vm.box = "msl0/node"
      node.vm.box_version = "1"
      node.vm.network "private_network", ip: "10.0.0.20"
  
      node.vm.provider "virtualbox" do |vb|
        vb.name = "node"
        vb.cpus = "1"
        vb.memory = "1024"
      end
    end
  
    config.vm.define "jenkins" do |jenkins|
      jenkins.vm.hostname = "jenkins"
      jenkins.vm.box = "msl0/jenkins"
      jenkins.vm.box_version = "1"
      jenkins.vm.network "private_network", ip: "10.0.0.10"
      jenkins.vm.network "forwarded_port", guest: 8080, host: 8082
      jenkins.vm.provider "virtualbox" do |vb|
        vb.name = "jenkins"
        vb.cpus = "1"
        vb.memory = "2048"
      end
    end
  end