version: "3.3"

services:
  db:
    image: mysql:5.7
    #volumes:
    #  - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: infoshare
      MYSQL_DATABASE: lms
      MYSQL_USER: lms
      MYSQL_PASSWORD: lms-pass
    ports:
      - "3306:3306"

  lms:
    depends_on:
      - db
    image: lms:v27-dev
    ports:
      - "81:80"
    restart: always
    environment:
      SQL_TYPE: mysql
      MYSQL_HOST: db
      MYSQL_DATABASE: lms
      MYSQL_USER: lms
      MYSQL_PASS: lms-pass
    links:
      - db