version: "3.6"

services:
  app:
    image: rstarmer/hostname:latest
    #ports:
    #  - 8080:80
    deploy:
      mode: replicated
      replicas: 3
      #placement:
      #  constraints: [node.role == manager]

  nginx-proxy:
    image: nginx
    ports:
      - 80:8080
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    command: [nginx-debug, '-g', 'daemon off;']
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]

#volumes:
#  myapp: