version: "3.8"
services:
  nfs:
    image: itsthenetwork/nfs-server-alpine
    container_name: nfs
    restart: unless-stopped
    privileged: true
    environment:
      - SHARED_DIRECTORY=/mnt/share
    volumes:
  
    ports:

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]