version: "3.8"
services:
  nfs:
    image: erichough/nfs-server
    container_name: nfs
    restart: unless-stopped
    privileged: true
    environment:
      - NFS_EXPORT_0='/mnt *(ro,no_subtree_check)'
    volumes:
      - /mnt:/mnt
    ports:
      - 2049:2049   
      - 2049:2049/udp
      - 111:111
      - 111:111/udp
      - 32765:32765
      - 32765:32765/udp
      - 32767:32767
      - 32767:32767/udp
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]