Vagrant.configure("2") do |config|
  config.vm.box = "debian/bullseye64"
  config.vm.network "forwarded_port", guest: 80, host: 20084
  config.vm.network "forwarded_port", guest: 81, host: 20085
  config.vm.network "forwarded_port", guest: 82, host: 20086
  config.vm.synced_folder "files", "/vagrant_data"
  config.vm.provider "virtualbox" do |vb|
    vb.name = "task-5"
    vb.memory = "2048"
  end
  config.vm.provision "shell", inline: <<-SHELL
    export DEBIAN_FRONTEND=noninteractive
    apt-get update
    apt-get install -y apache2 mc htop iptraf-ng iotop links
    mkdir /opt/mysql
  SHELL
  # Install Docker & Docker-compose
  config.vm.provision :docker
  config.vm.provision :docker_compose,
  yml: [
    "/vagrant/files/docker-compose.yml"
  ],
  run: "always"
end